@MyFirstWebApi_HostAddress = http://localhost:5254


### Obtener todas las tareas
GET {{MyFirstWebApi_HostAddress}}/api/todoitem
Accept: application/json

###

### Obtener una tarea por ID
GET {{MyFirstWebApi_HostAddress}}/api/todoitem/1
Accept: application/json

###

### Crear una nueva tarea
POST {{MyFirstWebApi_HostAddress}}/api/todoitem
Content-Type: application/json

{
  "title": "Aprender .NET 9",
  "isCompleted": false
}

###

### Crear otra tarea
POST {{MyFirstWebApi_HostAddress}}/api/todoitem
Content-Type: application/json

{
  "title": "Preparar ejercicio Web API",
  "isCompleted": false
}

###

### Actualizar una tarea existente
PUT {{MyFirstWebApi_HostAddress}}/api/todoitem/1
Content-Type: application/json

{
  "id": 1,
  "title": "Aprender ASP.NET Core 9",
  "isCompleted": true
}

###

### Eliminar una tarea
DELETE {{MyFirstWebApi_HostAddress}}/api/todoitem/2

###

### Intentar obtener una tarea no existente
GET {{MyFirstWebApi_HostAddress}}/api/todoitem/999
Accept: application/json

